### ISSUE TITLE
Restore testing and benchmark for HACLv2

### ISSUE THREAD

**Issue by beurdouche** [hacl-star/hacl-star#147]
We should restore performance and tests against `other_providers`

**Comment by msprotz** [comment]
There are now several performance testing frameworks for HACL*.
- @polubelova has a fork of SUPERCOP that can benchmark HACL*, so this provides extensive coverage against other implementations... it's slightly out of date, we could conceivably revive it if someone volunteers
- Cryspen maintains downstream performance testing via cryspen/hacl-packages
- Mozilla and Tezos also keep an eye on performance regressions.

Like with CI on different toolchains (#93), we agree that it'd be nice to have all of those in hacl-star/hacl-star, especially to have visibility on performance regressions in PRs. But alas, we currently lack the manpower to do so. Let's reopen this if anyone has concrete plans.
