### ISSUE TITLE
Dependency computation performance

### ISSUE THREAD

**Issue by wintersteiger** [hacl-star/hacl-star#212]
Yes, I know about `NODEPEND=1`, still, this seems a bit excessive...

```
[FSTAR-DEPEND (make)], 0:41.34
[FSTAR-DEPEND (full)], 0:53.41
[VALE-DEPEND], 2:26.91
...
[FSTAR-DEPEND (make)], 0:40.31
[FSTAR-DEPEND (full)], 0:52.47
[VALE-DEPEND], 2:26.39
```

Is anybody working on this or should I take a look?

**Comment by msprotz** [comment]
This is what I'm observing on my laptop:
```
[FSTAR-DEPEND (make)], 0:18.15
[VALE-DEPEND], 0:06.89
[FSTAR-DEPEND (full)], 0:24.71
```

this is after a lot of performance improvements in that area (previously, the numbers were much higher).

Some observations:
- vale-depend is clearly off the charts, it should not take that long
- your machine is much slower than my mid-2015 OSX laptop -- what could it be?
- on my machine, this is slower than a few months ago -- it used to be 11s, but it could just be that there's many more files now in the HACL* repository

No one is actively working on it; I would suggest trying to figure out why Vale is off the charts, then looking at some profiling see if there's some things that can be improved in the dependency analysis.

Thanks for looking at it!

Jonathan

**Comment by msprotz** [comment]
To be filed as an F* issue if anyone feels like it... not specifically a HACL* issue.
