### ISSUE TITLE
Support for post-quantum crypto?

### ISSUE THREAD

**Issue by jon-chuang** [hacl-star/hacl-star#228]
What is the timeline for supporting post-quantum crypto? 

This could be of mid-level priority because post-quantum KEMs and signatures already have implementations, some as part of a fork of OpenSSL/OpenSSH (https://github.com/open-quantum-safe) or AWS' TLS implementation s2n (https://github.com/awslabs/s2n). Within a few years, these primitives may be standardised and start being deployed. 

In particular, hybrid algorithms hedge against attacks against these new algorithms while hopefully protecting against quantum attacks.

I would be interested in doing a port of KEMs and signatures from some of these C implementations to HACL* and to work with the verification tools provided as part of project Everest. 

If I meet with success and am feeling adventurous, I may venture into ValeCrypt (or F* assembly?) waters and port assembly.

This could become a good jumping off point for future work on post-quantum crypto in project Everest, as many of the proposed systems use the same underlying math.

**Comment by s-zanella** [comment]
We are interested in verifying post-quantum cryptographic primitives and we already started working on this. So far, we have:

- A fully-verified implementation of FrodoKEM in `master` (https://github.com/project-everest/hacl-star/tree/master/code/frodo) 
- An implementation of QTesla verified for memory-safety: https://github.com/project-everest/hacl-star/tree/_dev/code/experimental/qtesla

You're more than welcome to contribute porting other implementations or improving the ones we have. There is still a lot to do. Using ValeCrypt to implement core algorithms for specific architectures would be a good way to improve performance.

I don't know if your GitHub profile is up to date, but if you're in Cambridge, you can drop some time by the Microsoft Research lab to have a chat about this.

**Comment by jon-chuang** [comment]
Hi Santiago, 

Perhaps I could look into extending the work on QTesla since I am familiar with RLWE. I suppose I am interested in SIKE as well, but I do not have good knowledge of elliptic curves, let alone isogenies. Perhaps this could be something for much later. Do you have any thing you think is worth looking into for QTesla?

I am currently busy with some other work and projects, so I can't start on this immediately, but perhaps we could have a chat perhaps in a month or so's time? 

I'll drop you an email once I am available.

Best,
Jonathan

**Comment by s-zanella** [comment]
> Do you have any thing you think is worth looking into for QTesla?
Proving functional correctness besides memory safety.

> I'll drop you an email once I am available.
Looking forward to discussing this with you.

**Comment by msprotz** [comment]
Let's close this in favor of more concrete issues for specific algorithms. It looks like the original question was answered.
