### ISSUE TITLE
Interest of HACL team in other curve-based crypto?

### ISSUE THREAD

**Issue by jon-chuang** [hacl-star/hacl-star#267]
I am interested in writing and verifying pairing-based crypto based on curves BLS12, KSS-16, BLS24. 

Beyond that, SIKE is on the table too (but this will, if at all, be a long time coming).

**Comment by karthikbhargavan** [comment]
We're certainly interested in SIKE/BLS etc. Depending on what you start working on, give us a ping in case we already have components you can reuse.

**Comment by msprotz** [comment]
Looks like the original question was answered, closing this until we have a concrete issue to file. Thanks.
