### ISSUE TITLE
Functional Verification of Rust Crypto

### ISSUE THREAD

**Issue by jon-chuang** [hacl-star/hacl-star#277]
I am wondering what the interest in the Everest team in targetting Rust. Rust is used extensively in the blockchain community for cryptographic implementation due to it's type safety and competitive performance with C++/C. A lot of new crypto (MPC, pairings, aggregated signatures, VDFs) is being implemented by this community. Just like with candidate post-quantum crypto, this presents an opportunity to test how verification applies to a wider subset of crypto.

Some very fast standard crypto has been implemented with Rust (e.g. [Curve25519 with AVX512-IFMA intrinsics](https://medium.com/@hdevalence/even-faster-edwards-curves-with-ifma-8b1e576a00e9)). It also goes without saying that verification tooling for Rust targetted at crypto is desirable. On the other hand, there has been some success implementing annotation-based functional verification in pure rust ([Prusti](https://github.com/viperproject/prusti-dev)). There has also been a popular Rust+ASM port of BoringSSL, [ring](https://github.com/briansmith/ring).

I am wondering what the naive points of intersection between project Everest and rust crypto could be. 

For instance, some integration of Prusti and Vale, for verifying Rust + inline assembly may be desirable.  A similar strategy to Evercrypt might be attempted, lifting Vale into Prusti, although there could be many hiccups since the underlying verification system is different. I understand that for Evercrypt, proofs of compatibility between the different specifications of the underlying memory model was possible due to these specifications both being written in F*. 

Perhaps something less ambitious that does not assume such a proof and only checks consistency between pre and post conditions can be made.

This does not necessarily have to be a part of the larger Evercrypt project. I foresee such a project taking off in a separate codebase and maintained by rust crypto practitioners but which leverage significant amounts of the tooling and strategies in Evercrypt.

**Comment by aep** [comment]
That would be unfortunate if hacl would stop targeting portable C. We're using it specifically because it exports to C, matching the strategy taken by github.com/zetzit

**Comment by beurdouche** [comment]
> That would be unfortunate if hacl would stop targeting portable C and depend on rust runtimes.  We're using it specifically because it exports to C, matching the strategy taken by [zetz](https://github.com/zetzit/zz)

That is certainly not an intent. The main target remains C for us because that’s what we massively use in prod. 
That said, the automated generation of a Rust binder on top of the C code might be nice addition for some use-cases.

**Comment by franziskuskiefer** [comment]
I'm working on Rust bindings here https://github.com/franziskuskiefer/evercrypt-rust/ (we should eventually move the -sys crate in here).

**Comment by msprotz** [comment]
The original question can now be answered in two ways.
- We have official Rust bindings in several places... the evercrypt-rust crate that Franziskus mentioned above, and the in-progress hacl-rust crate here: https://github.com/cryspen/hacl-packages/tree/main/rust
- Furthermore, we have two new tools that address the verification of Rust programs. Hacspec is a tool for writing specifications in Rust, while Aeneas is a tool for writing and verifying low-level programs in Rust.

We hope that these can serve as good new toolchains. In any case, if you have a specific piece of Rust code that you would like to verify, we're certainly interested in good benchmarks for the Aeneas tool, so please get in touch with us.

CCing @sonmarcho who might be interested
