### ISSUE TITLE
Target SSE4.2/SSSE3 instead of AVX? (for 128bit vectorized impls)

### ISSUE THREAD

**Issue by sopium** [hacl-star/hacl-star#317]
I tried to build them with `-msse4.2` (for poly1305) or `-mssse3` and there doesn't seem to be any problems, or performance losses. So it seems you are not actually using AVX(-only) instructions, just using VEX-encoded SSE instructions?

And there are plenty of processors with SSE4.2 support but no AVX support, e.g. all recent Intel Pentium and Celeron processors. On the other hand, many processors that support AVX also support AVX2.

So why not target SSE4.2/SSSE3?

**Comment by msprotz** [comment]
That's a good question. I don't have a good enough understanding of processor lineups to figure out whether picking, say, SSSE3 is a superior choice that will make our code run on more processor revisions.

@polubelova or @karthikbhargavan

**Comment by beurdouche** [comment]
We need to document lib_intrinsics.h to document which registers are needed by which Lib.Intvector functions.

I think that I have a similar issue with Firefox on Intel Gold or something where the build system requests AVX while the code could run with SSE4.1/2 hence falling back to the scalar code instead of vectorized code.

I’ll have another look...

**Comment by msprotz** [comment]
Does AVX imply SSSE3?

My recollection of what's being done in Firefox now is that the build and code are consistent, and the code is compiled with `-mavx` and then called only AVX is detected at run-time. I guess we could change our story to compile our code with, say, -mssse3 and do feature detection for SSSE3 at the EverCrypt level. (And change the NSS build flags and run-time detection accordingly.)

The bad case is if you compile with -mssse3 and -mavx, but only run-time check for the presence of SSSE3 when calling the code -- this allows the compiler to generate vectorized instructions for AVX even though it could have used equivalent instructions from the SSSE3 set. (This is the case we must avoid.)

**Comment by msprotz** [comment]
@franziskuskiefer is this something that hacl-packages can address?

**Comment by franziskuskiefer** [comment]
hacl-packages doesn't actually check for avx when looking for vec128. It is only enabled for vec256 (together with avx2).
vec128 on x86/64 currently checks for SSE2, SSE3, SSE4.1, and SSE4.2 (see [vec128.c] and [CMakeLists.txt]).

[vec128.c]: https://github.com/cryspen/hacl-packages/blob/d8e3f1a4ac1c4a89540cc888455247ed88437fb1/config/vec128.c
[CMakeLists.txt]: https://github.com/cryspen/hacl-packages/blob/d8e3f1a4ac1c4a89540cc888455247ed88437fb1/CMakeLists.txt#L194

**Comment by msprotz** [comment]
Build working properly in hacl-packages... from here on, the build of the dist/ folder is only for internal development and as such I don't see this as a dealbreaker. But I'll, of course, happily take a PR to fix this line: https://github.com/hacl-star/hacl-star/blob/main/dist/configure#L404

thanks!
