### ISSUE TITLE
Update Tutorial

### ISSUE THREAD

**Issue by jkzinzindohoue** [hacl-star/hacl-star#34]
Check that the small tutorial (`doc/tutorial`) is still working
Update with new content.

**Comment by msprotz** [comment]
The old tutorial referred to in this issue is at https://github.com/hacl-star/hacl-star/tree/dev/doc/tutorial and is outdated because it uses FStar.Buffer from six years ago. Closing this, and we'll maybe craft some fresh material at some point in the future.
