### ISSUE TITLE
misleading variable name(s) in Evercrypt_Ed25519.h header

### ISSUE THREAD

**Issue by niekbouman** [hacl-star/hacl-star#366]
Hi Evercrypt maintainers,

I noticed that in some function prototypes in the header file Evercrypt_Ed25519.h , which is merely a wrapper around Hacl's Ed25519 code, a misleading name is used for some parameters.

For example:
```cpp
bool EverCrypt_Ed25519_verify(uint8_t *output, uint32_t len, uint8_t *msg, uint8_t *signature);
```
while 'output' is incorrect here; it is in fact not an output but the public key input, thus the prototype should be:
```cpp
bool EverCrypt_Ed25519_verify(uint8_t *pub, uint32_t len, uint8_t *msg, uint8_t *signature);
```

I have not checked whether the same issue is present in other headers as well.

Of course this is not a bug, because the compiler ignores those names, but it might confuse users of the library.

best regards,
Niek

**Comment by msprotz** [comment]
This one was fixed by @polubelova and documentation was added too. This is part of a more general issue about consistent naming which is addressed in #675
