### ISSUE TITLE
Add 32-bit ARM cross builds

### ISSUE THREAD

**Issue by franziskuskiefer** [hacl-star/hacl-star#373]
We can't fully test 32-bit ARM but we should at least have a cross-compilation target on CI. This requires to add 32-bit ARM cross compilation support first.

cc @msprotz

**Comment by msprotz** [comment]
I believe this is now fixed in hacl-packages, right @franziskuskiefer ?

**Comment by franziskuskiefer** [comment]
I think arm32 got killed along the way because no one cared. We do arm64.
If there's anyone interested in arm32, we should talk about it to see how to get it on the roadmap.

**Comment by msprotz** [comment]
Feel free to close this issue, then, if there are no immediate plans

**Comment by franziskuskiefer** [comment]
Closing this for now until someone's asking for arm32.
