### ISSUE TITLE
EverCrypt_CTR_update_block fails to update internal counter in CHACHA20-mode

### ISSUE THREAD

**Issue by niekbouman** [hacl-star/hacl-star#392]
~~This error was caused due to incorrect use on my side.Apologies!~~

Sorry again for the confusion. I was confused myself and thought the problem was solved, but I still think there is an issue with CTR mode when using  CHACHA20 agility.

I have made small test case in c++, which calls `EverCrypt_CTR_update_block` ten times in succession:
```cpp
#include "EverCrypt_CTR.h"
#include "Hacl_Spec.h"
#include "Lib_RandomBuffer_System.h"

#include <array>
#include <iostream>

int main() {

    EverCrypt_CTR_state_s* state_ptr;
    std::array<uint8_t, 32> key {};
    std::array<uint8_t, 16> zeros {};
    std::array<uint8_t, 12> iv {};
    std::array<uint8_t, 16> ciphertext {};

    Lib_RandomBuffer_System_randombytes(key.data(), key.size());
    // randomize 256-bit key
    
    EverCrypt_AutoConfig2_init();
    EverCrypt_Error_error_code ret = EverCrypt_CTR_create_in(Spec_Agile_Cipher_CHACHA20, &state_ptr, const_cast<uint8_t*>(key.data()), iv.data(), sizeof(iv), 0U);

    if(ret)
    {
      std::cout << "init error: " << ret << '\n';
      return 1;
    }

    for (int i = 0; i < 10; ++i)
    {

        EverCrypt_CTR_update_block(state_ptr, ciphertext.data(), zeros.data());

        std::cout << "output: ";
        for (int byte : ciphertext)
        {
          std::cout << std::hex << byte << ", ";
        }
        std::cout << '\n';

    }

    EverCrypt_CTR_free(state_ptr);
    return 0;
}
```
The program has the following output, where the pattern (_not the actual random values_) is relevant:
the second output is different from the first, but then the output does not change anymore.
```
output: 73, f0, f1, 9b, 4a, 1d, 11, 76, df, 67, f8, c6, a3, 58, 8c, 5f, 
output: 43, f6, 26, 87, cd, 5b, 44, ce, 97, eb, ae, 61, 67, 8b, 24, b7, 
output: 43, f6, 26, 87, cd, 5b, 44, ce, 97, eb, ae, 61, 67, 8b, 24, b7, 
output: 43, f6, 26, 87, cd, 5b, 44, ce, 97, eb, ae, 61, 67, 8b, 24, b7, 
output: 43, f6, 26, 87, cd, 5b, 44, ce, 97, eb, ae, 61, 67, 8b, 24, b7, 
output: 43, f6, 26, 87, cd, 5b, 44, ce, 97, eb, ae, 61, 67, 8b, 24, b7, 
output: 43, f6, 26, 87, cd, 5b, 44, ce, 97, eb, ae, 61, 67, 8b, 24, b7, 
output: 43, f6, 26, 87, cd, 5b, 44, ce, 97, eb, ae, 61, 67, 8b, 24, b7, 
output: 43, f6, 26, 87, cd, 5b, 44, ce, 97, eb, ae, 61, 67, 8b, 24, b7, 
output: 43, f6, 26, 87, cd, 5b, 44, ce, 97, eb, ae, 61, 67, 8b, 24, b7,
```
It seems from inspecting the hacl/evercrypt source code, that the counter-value from the internal state is not updated in CHACHA20 mode.

**Comment by msprotz** [comment]
Hi Niek,

Yes, that seems incorrect. It looks like the counter argument should be `c0`, then the state should be updated to bump the counter. This module is unverified (per the documentation) because it was a placeholder for the QUIC work (see the S&P'21 paper) which needed a CTR-mode.

We currently don't have an owner for this module and it would need a significant amount of work to be fully verified. What I can do, however, is try to provide a quick fix that would continue to be unverified.

Would that work for you?

Thanks,

Jonathan

**Comment by niekbouman** [comment]
Hi Jonathan,

Thank you very much for your response.

> What I can do, however, is try to provide a quick fix that would continue to be unverified.
> Would that work for you?

Yes such a fix would be very welcome, and I guess that other users would benefit from this as well.

Currently, I use the following workaround:
```cpp
       EverCrypt_CTR_update_block(state_ptr, /* ...other args... */);
        if (chacha20_mode) {
            ++(state_ptr->ctr);
            // work-around: counter is not updated in CHACHA20 mode
        }
```
which means that I need to repeat the definition of EverCrypt_CTR_state_s in my own code, in order to be able to access the `ctr` struct member:
```cpp
// access to internal state needed to work around bug in CHACHA20-mode:
// https://github.com/project-everest/hacl-star/issues/392
typedef struct EverCrypt_CTR_state_s_s {
    Spec_Cipher_Expansion_impl i;
    uint8_t* iv;
    uint32_t iv_len;
    uint8_t* xkey;
    uint32_t ctr;
} EverCrypt_CTR_state_s;
// (end of work-around)
```

which is a bit brittle (defining the same thing at two places) and goes against encapsulation.
With your fix I would no longer need this workaround.

**Comment by msprotz** [comment]
Transferring this issue to project-everest/everquic-crypto
