### ISSUE TITLE
Multiplexing for Blake2 API in EverCrypt

### ISSUE THREAD

**Issue by victor-dumitrescu** [hacl-star/hacl-star#473]
Blake2b and Blake2s have been included in the EverCrypt hashing interface, but only their portable C versions. This means that users wanting to use the fastest Blake2b implementations where possible need to check this in their code. It also means that it is not possible to use the streaming interface with the faster versions where possible.

I'm opening this issue because these are both things that would be useful for us to have in Tezos.

**Comment by msprotz** [comment]
Fixed in https://github.com/hacl-star/hacl-star/pull/623
