### ISSUE TITLE
About the Evercrypt. AEAD file

### ISSUE THREAD

**Issue by 15646739752** [hacl-star/hacl-star#525]
Hi，
If I want to achieve AES encryption and decryption, which functions in this file need to be called? I do not understand the functions of each function in AEDE, I hope to get your answers, thank you

**Comment by msprotz** [comment]
We currently don't expose standalone AES and recommend the AEAD construction for all your needs. Have you seen https://hacl-star.github.io/EverCryptAEAD.html?

**Comment by 15646739752** [comment]
Yes, but I'm a little confused about this. For example, the EverCrypt AEAD create in function implements the key extension, and the encryption and decryption function uses the extended key, but there is no connection between the return value of the two functions.

**Comment by msprotz** [comment]
What do you mean there is no connection? `EverCrypt_AEAD_create_in` modifies its `dst` parameter. Sketch:

```
EverCrypt_AEAD_state *st = NULL;
if (EverCrypt_AEAD_create_in(Spec_..._AES128_GCM, &st, key) != EverCrypt...Success)
  // handle error
if (EverCrypt_AEAD_encrypt(st, ...) != EverCrypt_...Success)
 // handle error
```

**Comment by 15646739752** [comment]
Yeah, I mean the extended key that's used in the decryption function, how is it passed from EverCrypt AEAD create in to the decryption function

**Comment by msprotz** [comment]
Same as with my encrypt example above? See my usage of `st`

**Comment by 15646739752** [comment]
Thank you for your answer, I still have some places I don't understand, such as:
1. I don't know what some parameters are: AD,plain, cipher
2. Some functions called in decryption functions, such as GCM128 Decrypt opt, AES256 key Expansion, I can only find their references in vale.h, there is no specific function body

**Comment by Frosne** [comment]
Hello :) 

I will try to answer the first question: 
AEAD is authenticated encryption with associated data. So you have two components - a message that will be encrypted and some associated data. The associated data WILL NOT be encrypted, but it could be authenticated. The message to encrypt should be in the buffer plain, the associated data in is AD. 

Then, the encryption produces a result. The result is written down to the cipher buffer.

**Comment by Frosne** [comment]
There are some cases when you don't need the AD buffer. It's possible not to use it.

**Comment by msprotz** [comment]
Regarding the second point, if the functions are not exposed in EverCrypt_AEAD.h then you should not use them -- Vale.h is an internal header and you are not expected, as a client of the library, to be using these functions directly.

**Comment by 15646739752** [comment]
Thank you for your answer to the first point. As for the second point, I cannot directly use the functions called by EverCrypt aead. c functions. In this case, can the encryption and decryption function be normal? Or do I just call the function in EverCrypt aad.c and not worry about the function call?

**Comment by msprotz** [comment]
We have now documented the header file extensively. Please file a separate issue if the documentation is not helpful here: https://github.com/hacl-star/hacl-star/blob/main/dist/gcc-compatible/EverCrypt_AEAD.h

Thanks
