### ISSUE TITLE
Building HACL* w/o Vale

### ISSUE THREAD

**Issue by concatime** [hacl-star/hacl-star#528]
Hi there,
have you considered making Vale optional in the build process?
Because otherwise, this project is not bootstrapable. In fact, I compiled
OCaml, F*, Kremlin, mono. But lastly, F# depends on msbuild, which,
AFAIK isn't even bootstrapable right now [1] [2] ! Which makes HACL*
un-bootstrapable, thus not usable by any sane distro.
Thank you!

[1] https://github.com/mono/linux-packaging-msbuild/issues/11
[2] https://github.com/mono/linux-packaging-msbuild/issues/1

**Comment by msprotz** [comment]
@Chris-Hawblitzel is the Vale tool expert, here... Chris, any thoughts?

**Comment by Chris-Hawblitzel** [comment]
My recommendation so far has been for people to use the Vale .NET binary, which should be platform neutral and should depend only on mono.  Do you need F# to use Vale?

**Comment by concatime** [comment]
Well, I will be using the binaries provided for now. But relying on third-party provided binaries is the opposite of bootstrapable.

**Comment by msprotz** [comment]
I think all of this should be obsolete now with the advent of dotnet, right? Closing, since we do not have much control over msbuild in any case. Thanks.
