### ISSUE TITLE
Memory usage issues throughout the build

### ISSUE THREAD

**Issue by msprotz** [hacl-star/hacl-star#541]
I had fun this afternoon and monitored a full build of HACL* on my machine to see who were the worst offenders in terms of memory usage... this is a recurring complaint (CI builds severely limited in parallelism because of occasional bursts in memory consumption; students can't run a full build with -j 2 on their medium-end laptops; etc.).

Here's what I did:
- ran a build of HACL*
- ran a sample every 1s to get the process on my machine that consumes the most memory (highest RSS): `rm -rf log; while true; do ps -x -o rss -o command | sort -n | tail -n 1 | tee -a log; sleep 5; done`
- sort and print: `sort -r ~/log -n | sort -s -k 2 | uniq -f 1 | sort -n | awk '{ print $1, $NF }' | sed 's/hints.\(.*\).hints/\1/g'`

For the sample: use a custom `ps` invocation that only prints RSS and the command; sort numerically; keep the highest one; append to the log file.

For the sort and print: sort the samples by highest RSS first; then sort using a stable sort using only the invocation; this means that the entries are now grouped by command, and for each file, the highest RSS comes first; then keep unique entries based only on the command; sort numerically again; keep only first and last fields; trim.

The result -- first column is in byte, I manually edited this to make it more apparent how big the memory usage was.

```
1,930,092 Hacl.Spec.Bignum.Definitions.fst
2,020,592 Vale.Transformers.InstructionReorder.fst
2,070,856 Vale.AES.X64.AESGCM.fst
2,302,672 Vale.Poly1305.X64.fst
2,704,552 Spec.P256.MontgomeryMultiplication.PointAdd.fst
3,528,656 Vale.Wrapper.X64.GCMdecryptOpt.fst
3,899,972 Vale.AES.X64.GCMencryptOpt.fst
3,916,500 Vale.AES.X64.GCMdecryptOpt.fst
4,043,888 Hacl.Test.ECDSA.fst
4,119,032 Vale.Curve25519.X64.FastHybrid.fst
4,976,700 Hacl.Test.HMAC_DRBG.fst
11,115,828 Hacl.Impl.P256.LowLevel.fst
```

Some interesting takeaways:
- very few invocations of F* actually go beyond 2GB
- there are a few offenders in the 5GB ballpark
- one single file is clearly an outlier. See #539 

This is obviously an approximation; I probably should have used `tail -n 5` to be more accurate... I can re-do that at a later point, because this may have missed some files. But this is pretty informative already.

**Comment by msprotz** [comment]
Update: ran with `-n 5` as promised, here's a more precise count. This lists all of the files that ended up peaking above 2GB of memory. Surprisingly few of those!

```
2,263,476 Vale.AES.X64.AESGCM.fst
2,368,652 Vale.Poly1305.X64.fst
2,671,768 Hacl.Impl.SHA2.Core.fst
3,376,952 Vale.Wrapper.X64.GCMdecryptOpt256.fst
3,491,508 Vale.Wrapper.X64.GCMencryptOpt256.fst
3,501,196 Vale.Curve25519.X64.FastUtil.fst
3,508,300 (fstar.exe)
3,516,564 Vale.Wrapper.X64.GCMencryptOpt.fst
3,549,684 Vale.Wrapper.X64.GCMdecryptOpt.fst
3,821,796 Vale.Curve25519.X64.FastHybrid.fst
3,824,408 Vale.AES.X64.GCMencryptOpt.fst
3,897,656 Vale.AES.X64.GCMdecryptOpt.fst
3,938,032 Vale.Curve25519.X64.FastSqr.fst
4,238,168 Hacl.Test.ECDSA.fst
5,198,160 Hacl.Test.HMAC_DRBG.fst
5,784,732 Test.Vectors.fst
11,250,172 Hacl.Impl.P256.LowLevel.fst
```

**Comment by msprotz** [comment]
```
2,172,040 Hacl.Impl.P256.LowLevel.fst
2,178,808 Vale.Curve25519.X64.FastMul.fst
2,234,952 Vale.AES.X64.AESGCM.fst
2,411,460 Vale.Poly1305.X64.fst
2,465,716 Spec.P256.MontgomeryMultiplication.PointAdd.fst
2,491,804 Hacl.Impl.SHA2.Core.fst
2,655,512 Hacl.Spec.K256.Field52.Lemmas3.fst
3,424,432 Vale.Wrapper.X64.GCMencryptOpt.fst
3,459,308 Vale.Curve25519.X64.FastUtil.fst
3,524,508 Vale.Wrapper.X64.GCMencryptOpt256.fst
3,678,088 Vale.Wrapper.X64.GCMdecryptOpt.fst
3,730,196 Vale.Wrapper.X64.GCMdecryptOpt256.fst
3,893,544 Vale.AES.X64.GCMdecryptOpt.fst
3,925,760 Vale.AES.X64.GCMencryptOpt.fst
3,936,032 Vale.Curve25519.X64.FastSqr.fst
4,151,604 Vale.Curve25519.X64.FastHybrid.fst
4,398,368 Test.Vectors.fst
5,009,852 Hacl.Test.HMAC_DRBG.fst
5,782,072 Hacl.Test.ECDSA.fst
```

this is a massive improvement for P256.

**Comment by karthikbhargavan** [comment]
I am happy to try re-fixing this proof, but it would be useful to get some guidance on what blows up memory usage here, so that I or others don't re-introduce any "bad" patterns in HACL*. Do you or Aseem have an explanation on what patterns we should not use and what the typical fix would be ? I can then implement it here, and this Issue and PR #556  can serve as a guide on what to do in such cases.

**Comment by msprotz** [comment]
Closing since the file is now gone. @pnmadelaine you might find the commands interesting to monitor memory usage throughout the build; they're for OSX but can be easily adapted for a GNU userland, I'm sure
