### ISSUE TITLE
Shebang + `/usr/bin/env` not available everywhere (hacl-star-raw opam package)

### ISSUE THREAD

**Issue by vapourismo** [hacl-star/hacl-star#548]
The configure script that ships with the `hacl-star-raw` opam package [relies on the shebang and `/usr/bin/env`](https://github.com/project-everest/hacl-star/blob/master/dist/configure#L1) to dispatch itself to `bash`. Unfortunately `/usr/bin/env` is not available on every platform. 

Would it be possible to dispatch to `bash` directly instead? [For example like this.](https://github.com/vapourismo/opam-repository/commit/ccb4df69f20af40a030e621674285e3a1c144bcd)

I know this is a little unorthodox and usually I would rely on patching the source. However, it seems that the package ships with a checksum mechanism that makes this a little awkward - maybe I am missing something.

Appreciate any input!

/cc @victor-dumitrescu

**Comment by msprotz** [comment]
Thanks for the report. Which systems don't have /usr/bin/env? The advantage of using `env` (see https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my/29620#29620) is that on systems that have multiple versions of bash, it picks the one that comes first in the user's PATH as opposed to hardcoding a particular location. For instance, on OSX, /bin/bash is a version from 15 years ago whereas oftentimes /usr/local/bin/bash exists and is much more recent.

My only concern is that, say, on OSX (again), this would mean that OPAM runs the configure script with bash 3.2 whereas I (and others) would only be testing it with bash 5 and above. This might lead to inconsistencies and/or bugs not being caught. Of course this can all be addressed with better CI but it'd help to know first which scenario (without env) we're addressing here. Thanks!

**Comment by vapourismo** [comment]
For context, this is the case when using Nix. In a Nix build environment the system-level directories are completely hidden to achieve build purity. That means `/usr/bin`, `/bin` and the like are unavailable.

I don't understand your point about the advantage of `env`. What you're describing seems to be the standard rule to resolve commands to their executables via `$PATH`, no? With that, `env bash` is identical to `bash` - the former will use `env` to look up `bash` in `$PATH` and the latter will use the current shell (i.e. `sh`) to lookup `bash` in the `$PATH` and both will choose the first occurrence. Wouldn't that mean that executing `bash ./configure` is identical to running `./configure` as long as `/usr/bin/env` exists?
Apologies if I am missing something obvious.

---

For context, I tried it locally.

```bash
$ echo $PATH
/home/ole/.opam/default/bin:/run/wrappers/bin:/home/ole/.nix-profile/bin:/etc/profiles/per-user/ole/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/home/ole/.cabal/bin:/home/ole/.local/bin
$ which bash
/run/current-system/sw/bin/bash
$ realpath /run/current-system/sw/bin/bash
/nix/store/98lfv62phdndldvgpxmjp634cifqmk30-bash-interactive-5.1-p8/bin/bash

$ nix-shell -p bash # Start a new shell, with a different bash in scope.

[nix-shell:~]$ which bash # Shows different bash
/nix/store/fa138pjfv8b4sg5l80ls55ynz9g4s3p9-bash-interactive-5.1-p16/bin/bash

[nix-shell:~]$ echo $PATH # In-scope bash path is the first entry. The old entry is still there but comes later.
/nix/store/fa138pjfv8b4sg5l80ls55ynz9g4s3p9-bash-interactive-5.1-p16/bin:/nix/store/9chsm1gqvvpqywz219s1rknfrzr5xjfz-patchelf-0.14.3/bin:/nix/store/jz10kjr0lnhynwxnrzv4kcwbjs5s0ri8-gcc-wrapper-10.3.0/bin:/nix/store/finlf6zyxhpqi8hp2p4fgxkgqvjp6l78-gcc-10.3.0/bin:/nix/store/drb5a0j2z8fh6bivl9aq15fbfmrx62kb-glibc-2.33-117-bin/bin:/nix/store/2w6011wwg5v6qxz182r4d0mmr3i4rxm1-coreutils-9.0/bin:/nix/store/55ayck4pllh4qallb1dbhbkrzwrrl02r-binutils-wrapper-2.35.2/bin:/nix/store/x2zbyl2l4xayv4d5is0b31plfq8xjjym-binutils-2.35.2/bin:/nix/store/dndi916j6yxzfzzj2sma2llhrlwahq06-bash-5.1-p16/bin:/nix/store/2w6011wwg5v6qxz182r4d0mmr3i4rxm1-coreutils-9.0/bin:/nix/store/pr0l0cwak2dprcvvzqvli1kkpg7k9fci-findutils-4.9.0/bin:/nix/store/c5xa1n6bl34gxfmjlqgaxdyk4i583fk5-diffutils-3.8/bin:/nix/store/jdhk02s01ca02qv083f41wz8jj25gybc-gnused-4.8/bin:/nix/store/3fvq0jjjh50vh0rlqr2xc9ya8llcj113-gnugrep-3.7/bin:/nix/store/i4mm5ycljiq465ncr29mg9bf7wn18i8c-gawk-5.1.1/bin:/nix/store/4rypjibv28cbbg21apsqnnyi3k2glzjd-gnutar-1.34/bin:/nix/store/660k06nr64g3fqndivn6brmk8ly7ivdz-gzip-1.11/bin:/nix/store/rmxjjpg43f6jssh82q29q21lzlcqzwxz-bzip2-1.0.6.0.2-bin/bin:/nix/store/xgibf1z6b7zx4h1hv3v8qw0f2n1jv4pm-gnumake-4.3/bin:/nix/store/dndi916j6yxzfzzj2sma2llhrlwahq06-bash-5.1-p16/bin:/nix/store/agfkd1d9mmcniwrvh10afn054x1n8iqi-patch-2.7.6/bin:/nix/store/45j7wibbdckl5f50bs5nq7damhy8cahp-xz-5.2.5-bin/bin:/home/ole/.opam/default/bin:/run/wrappers/bin:/home/ole/.nix-profile/bin:/etc/profiles/per-user/ole/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/home/ole/.cabal/bin:/home/ole/.local/bin
```

**Comment by msprotz** [comment]
Sorry, I was talking about a hypothetical scenario which would be to replace the first line of the script with `/usr/bin/bash` -- I somehow assumed this was your preferred fix. I am actually fine with the suggested change for the OPAM file.

If @victor-dumitrescu is down for it, that's good for me!

Thanks for the suggested fix.

**Comment by vapourismo** [comment]
I managed to find a Nix-specific way to circumvent this problem. From my perspective this is now less of an issue.

---

For completeness' sake I am including the solution for whomever it may concern.

```nix
mkDerivation {
  # ...

  fixCargoChecksums = writeScript "fix-cargo-checksum" ''
    jq "{ package: .package, files: { } }" "$1" > "$1.empty"
    mv "$1.empty" "$1"
  '';

  postInstall = ''
    # Patch shebangs in shell scripts
    patchShebangsAuto

    # Fix Cargo checksum files (because we patched some files)
    find $out -name .cargo-checksum.json -exec $fixCargoChecksums {} \;
  '';

  # ...
}
```

**Comment by victor-dumitrescu** [comment]
Hi, thanks for opening the issue and sorry for the late reply. The solution you suggested seems reasonable. Just to be sure, I'd like to test it on all our other supported platforms before committing it to opam. If that's not urgent (as I think you suggest in the last comment) then I can do it next time we make a release. Would that be OK?

**Comment by vapourismo** [comment]
Yes absolutely!

**Comment by msprotz** [comment]
@victor-dumitrescu friendly ping on this issue... since you have other changes in the pipeline, maybe worth trying out this one too? thanks!

**Comment by TWal** [comment]
@vapourismo Did you see that HACL* was already packaged with Nix? https://github.com/hacl-star/hacl-nix/blob/main/hacl/default.nix
Other than that, I'm no Nix expert but I often saw fellow nixers advocating for `#!/usr/bin/env bash` instead of `#!/bin/bash`, and afterward use `patchSchebangs` in the Nix derivation.
Hence I think the issue can be safely closed, if I'm not mistaken?

**Comment by victor-dumitrescu** [comment]
In the meantime, there is a new build process and new packages over in https://github.com/cryspen/hacl-packages/ so I'm wondering how important the portability of the configure script here still is. If so, I can commit the `#!/usr/bin/env bash` solution.

**Comment by victor-dumitrescu** [comment]
Closing, as there seems to be another solution for this https://github.com/hacl-star/hacl-nix
