### ISSUE TITLE
Unaligned memory allocation in Blake2b Vec256

### ISSUE THREAD

**Issue by franziskuskiefer** [hacl-star/hacl-star#586]
`Hacl_Streaming_Blake2b_256_blake2b_256_no_key_create_in` uses `malloc` to allocate the vec256 state. This will lead to segmentation faults in most cases on x64 machines because the memory is not alligned.
All vec256 allocations in this function (and everywhere else) must be allocated using something that aligns memory like `_mm_malloc`, `aligned_alloc`, `posiz_memalign`, or `_aligned_malloc`.

https://github.com/project-everest/hacl-star/blob/82d4ba6f9e1710c78a494016896b8431d1c318c8/dist/gcc-compatible/Hacl_Streaming_Blake2b_256.c#L43

**Comment by msprotz** [comment]
Is there a recommended macro to figure out how to do aligned memory allocation on all platforms?

**Comment by msprotz** [comment]
The memory also needs to be freed with a special function at least in the case of MSVCRT

**Comment by franziskuskiefer** [comment]
I don't know of any macro or similar things to handle this. There are a couple ways I can imagine to implement it.
The existing krml macros could be changed to use aligned allocation depending on the platform and type. NSS for example uses pre and post align attributes https://searchfox.org/nss/source/lib/freebl/blapii.h#62-72 for single values.

Here's Intel's reference on memory alignment https://www.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/intrinsics/data-align-mem-alloc-intrins-and-inline-asmbly/alignment-support.html

**Comment by msprotz** [comment]
Does this mean if I have a struct that contains a vec256, I need to align it in the struct declaration *and* align the outer allocation?

```
typedef struct {
  KRML_PRE_ALIGN vec256 x KRML_POST_ALIGN;
} state;

...
state *s = KRML_ALIGNED_MALLOC(sizeof state);
...
KRML_ALIGNED_FREE(s);
```

Also, are you aware of any bit of configure code I could copy/paste to figure out what is the name of the aligned malloc function for a given platform? If not, I'll just pick some sane defaults, and anyone wishing to do something more sophisticated, e.g. via a cmake configuration phase, will be able to override the default choices by passing -DKRML_ALIGNED_MALLOC at compile-time.

**Comment by franziskuskiefer** [comment]
> Does this mean if I have a struct that contains a vec256, I need to align it in the struct declaration _and_ align the outer allocation?

This shouldn't be necessary. If you have the `vec256` in the first place here, it'll get the 0 offset into the struct, i.e. the address from `KRML_ALIGNED_MALLOC` and should hence be aligned. You can also put it at any offset `% 16 == 0`.

`aligned_alloc` is fine in [C11](https://en.cppreference.com/w/c/memory/aligned_alloc). If you want to have a fallback for older version like C89 you'll probably want to do it manually like [here](https://searchfox.org/nss/source/lib/util/secport.c#126) or [here](https://hg.mozilla.org/projects/nspr/file/tip/pr/src/malloc/prmalloc.c#l754).

**Comment by msprotz** [comment]
Sorry, I meant something like this:

```
typedef struct {
  // possibly more fields
  KRML_PRE_ALIGN vec256 x KRML_POST_ALIGN;
} state;

...
state *s = KRML_ALIGNED_MALLOC(sizeof state);
...
KRML_ALIGNED_FREE(s);
```

I guess I would then have to align it unless I statically know that it's on a 16 byte boundary? The safe thing is to always add the alignment declarations and let the compiler figure it out, I suppose.

**Comment by msprotz** [comment]
Thanks for the pointers on aligned malloc. Unsurprisingly, MSVC doesn't implement the C11-compliant `aligned_malloc`.

I would probably use `KRML_*` macros like in the example above, then add in the krml header:

```
#ifndef KRML_ALIGNED_MALLOC
#define KRML_ALIGNED_MALLOC aligned_malloc
#endif

#ifndef KRML_ALIGNED_FREE
#define KRML_ALIGNED_FREE free
#endif
```

and for the Windows CI, use `/DKRML_ALIGNED_MALLOC=_aligned_malloc /DKRML_ALIGNED_FREE=_aligned_free` directly in the compiler command-line (or in config.h or something)

**Comment by franziskuskiefer** [comment]
> I guess I would then have to align it unless I statically know that it's on a 16 byte boundary

Yes. You have to know the sizes in your struct that are in front of the memory you need aligned to make sure it is aligned.

**Comment by polubelova** [comment]
@franziskuskiefer: how does your PR close this issue in the main hacl-star repository?

**Comment by franziskuskiefer** [comment]
Sorry, I didn't expect that this will actually close this issue.

**Comment by msprotz** [comment]
This is now fixed.
