### ISSUE TITLE
CI support for extracting and testing HACL* with MSVC

### ISSUE THREAD

**Issue by beurdouche** [hacl-star/hacl-star#60]

**Comment by msprotz** [comment]
I thought we fought really hard with @tahina-pro to make this work... does it no longer work?

**Comment by beurdouche** [comment]
?? Maybe it is working, but I have no knowledge of HACL* being compiled with MSVC at the moment.

**Comment by msprotz** [comment]
There used to be this in the Makefile:
+       if $(HAS_CL); then USE_CL=true $(MAKE) extract-c ; fi^M
And then, a while ago, `extract-c` would also compile and run the tests. So yes, it definitely was on CI for a while.

**Comment by beurdouche** [comment]
Ok, I'll look into restoring it then. Thanks Jonathan !

**Comment by beurdouche** [comment]
@protz is MSVC covered by the CI these days ?

**Comment by msprotz** [comment]
Yes, as part of the Everest-wide Windows builds, we gather all the sources from Everest and recompile them with MSVC and run a few tests.

We don't have local HACL MSVC CI. It would be nice to have.

**Comment by msprotz** [comment]
MSVC is taken care of these days, so closing this issue
