### ISSUE TITLE
Remove unused `prev_len` argument in `Hacl_Hash_SHA2_update_last_*` functions

### ISSUE THREAD

**Issue by franziskuskiefer** [hacl-star/hacl-star#673]
Ugh. Thanks. Two thoughts:
- this argument is unused so conceivably we should be able to ditch that `prev_len`... can you file a separate issue for that?
- you should be using the streaming API directly, rather than using the low-level update/update_last API, shouldn't you?

_Originally posted by @msprotz in https://github.com/hacl-star/hacl-star/issues/617#issuecomment-1304617580_

**Comment by franziskuskiefer** [comment]
Maybe these functions should be dropped entirely (from the public API).

**Comment by msprotz** [comment]
Yeah I think that's the better fix. Also, I read quickly and this update_last which *does* need the final length, so let's hide these functions underneath the streaming API.

**Comment by msprotz** [comment]
My latest push in #670 hides Hacl.SHA2.Scalar32 behind Hacl_Streaming_SHA2

Now we need to rewire EverCrypt.Hash to use Hacl.SHA2.Scalar32.update and then we're good to go for this.

**Comment by msprotz** [comment]
That latter point was done in #756
