### ISSUE TITLE
Unused inclusion of wmmintrin.h

### ISSUE THREAD

**Issue by Frosne** [hacl-star/hacl-star#678]
Hello,

I think the wmmintrin.h intrinsics file included in libintvector.h (https://github.com/hacl-star/hacl-star/blob/74bc4d01a7ca88ae027336d29dc081cc93b992d6/dist/gcc-compatible/libintvector.h#L229) is not used, so it can be removed :) 

(This file contains aes + PCLMUL instrctions)

**Comment by msprotz** [comment]
Confirmed via https://github.com/cryspen/hacl-packages/actions/runs/3438700031 that this doesn't break the build
