### ISSUE TITLE
Defaulting `HACL_HOME` to `.` confuses `sed`

### ISSUE THREAD

**Issue by mtzguido** [hacl-star/hacl-star#682]
Hi, during a recent attempt at bisecting HACL I had a problem: I do not have HACL_HOME set in my shell (I used to until recently, but anyway), and this confuses the sed invocation that fixes the `.fstar-depend-full` file.

Since `Makefile.common` defines:
```make
HACL_HOME 	?= .

# Put your local configuration (e.g. HACL_HOME, KRML_HOME, etc.) in
# Makefile.config
-include $(HACL_HOME)/Makefile.config

KRML_HOME 	?= $(HACL_HOME)/../karamel
FSTAR_HOME	?= $(HACL_HOME)/../FStar
VALE_HOME	?= $(HACL_HOME)/../vale
```

and there's also:
```make
.fstar-depend-%: .FORCE
	@if ! [ -f .didhelp ]; then echo "💡 Did you know? If your dependency graph didn't change (e.g. no files added or removed, no reference to a new module in your code), run NODEPEND=1 make <your-target> to skip dependency graph regeneration!"; touch .didhelp; fi
	$(call run-with-log,\
	  $(FSTAR_NO_FLAGS) --dep $* $(notdir $(FSTAR_ROOTS)) --warn_error '-285' $(FSTAR_DEPEND_FLAGS) \
	    --extract 'krml:*' \
	    --extract 'OCaml:-* +FStar.Krml.Endianness +Vale.Arch +Vale.X64 -Vale.X64.MemoryAdapters +Vale.Def +Vale.Lib +Vale.Bignum.X64 -Vale.Lib.Tactics +Vale.Math +Vale.Transformers +Vale.AES +Vale.Interop +Vale.Arch.Types +Vale.Arch.BufferFriend +Vale.Lib.X64 +Vale.SHA.X64 +Vale.SHA.SHA_helpers +Vale.SHA2.Wrapper +Vale.SHA.PPC64LE.SHA_helpers +Vale.PPC64LE +Vale.SHA.PPC64LE +Vale.Curve25519.X64 +Vale.Poly1305.X64 +Vale.Inline +Vale.AsLowStar +Vale.Test +Spec +Lib -Lib.IntVector -Lib.Memzero0 -Lib.Buffer -Lib.MultiBuffer +C -C.String -C.Failure' > $@ && \
	  $(SED) 's!$(HACL_HOME)/obj/\(.*.checked\)!obj/\1!;s!/bin/../ulib/!/ulib/!g' $@ \
	  ,[FSTAR-DEPEND ($*)],$(call to-obj-dir,$@))
```

The `$(SED)` invocation unfolds (in my setup) to
```bash
 sed -i 's!./obj/\(.*.checked\)!obj/\1!;s!/bin/../ulib/!/ulib/!g' .fstar-depend-make
```
which roughly includes a replacement of `./obj/` for `obj/`, where the dot is wildcard, and replaces
```
/home/guido/r/everest/karamel/krmllib/obj/FStar.Krml.Endianness.fst.checked
```
for
```
/home/guido/r/everest/karamel/krmlliobj/FStar.Krml.Endianness.fst.checked
```
where `krmlliobj` of course does not exist!

I've worked around it by defining `HACL_HOME`. Maybe the default can be `$(pwd)` or `realpath .` instead of `.`? Or use some escaping? I am suddenly scared by dots in filenames due to this.

**Comment by msprotz** [comment]
Yeah this sed works around a long-standing F* issue that I think you reported first -- see my comment here https://github.com/FStarLang/FStar/issues/1978#issuecomment-607577934

Maybe fixing the underlying F* issue would be a win for all projects. I wonder how many folks are aware of this shortcoming and are running a proper sed to get a correct build.

Barring that, would escaping the `.` work in this scenario, though? Maybe defining HACL_HOME to $(shell pwd) is better... Thoughts?

**Comment by msprotz** [comment]
Great! Can you confirm that fix works for you? (the `$(shell pwd)` fix)

**Comment by mtzguido** [comment]
Yes, seems to work for me on Linux.
