### ISSUE TITLE
Compiling gcc-compatible without optimizations

### ISSUE THREAD

**Issue by Moschn** [hacl-star/hacl-star#736]
When compiling Evercrypt without optimizations and without VALE support, the compilation fails. The main issue is that [EverCrypt_Poly1305.c](https://github.com/hacl-star/hacl-star/blob/8c77ca1d9ae956ec099b38a02022c18bb20c86be/dist/gcc-compatible/EverCrypt_Poly1305.c) has a define guard for VALE, but the define guard only guards calling the VALE function. The actual function (`poly1305_vale`) still exists. With higher optimization levels (I tested `-O2` and `-O3`), the compilation succeeds. This is probably due to compiler optimizations that remove the unused function. 

I have no experience in F* so I did not attempt to fix it, but I would assume an additional guard in [EverCrypt.Poly1305.fst](https://github.com/hacl-star/hacl-star/blob/8c77ca1d9ae956ec099b38a02022c18bb20c86be/providers/evercrypt/fst/EverCrypt.Poly1305.fst) should do the job.

**To Reproduce**
1. Commit: 8c77ca1d9ae956ec099b38a02022c18bb20c86be
2. Change the optimization level in the [Makefile](https://github.com/hacl-star/hacl-star/blob/8c77ca1d9ae956ec099b38a02022c18bb20c86be/dist/gcc-compatible/Makefile)
3. Call `make`
4. Observe linker error: `EverCrypt_Poly1305.c:46: undefined reference to 'x64_poly1305'`

**Platform:**
 - OS:Linux
 - Architecture: I am cross-compiling to riscv but I observe the same behavior on x86

**Comment by msprotz** [comment]
I was able to reproduce by exporting MARCH=foobar to prevent the assemblies from being linked in (and thus hiding the error).

Nice catch! Thanks for the report.

**Comment by Moschn** [comment]
Thanks for the quick fix! I thin this can be closed
