### ISSUE TITLE
feat: Add `without_key` and `with_key` functions to BLAKE2{b,s}.

### ISSUE THREAD

**Issue by duesee** [hacl-star/hacl-star#788]
**Is your feature request related to a problem? Please describe.**

While thinking about how to improve the Hash APIs in HACL*, we noticed that certain functions in BLAKE2{b,s}{,Simd} are missing. Concretely (with `Blake2b_32` as example) ...

*One-Shot*

* `Hacl_Blake2b_32_blake2b` always takes a key and there should be a function that doesn't, i.e., a wrapper that calls this function with a zero-length key.

*Streaming / Incremental*

* `Hacl_Streaming_Blake2_blake2b_32_no_key_create_in()` doesn't take a key and there should be a function that does.
* `Hacl_Streaming_Blake2_blake2b_32_no_key_init(s1)` doesn't take a key and there should be a function that does.

For better readability, I appended our *draft* proposal to do some renamings. I think it makes it easier to see why those functions should be added. To be clear: This PR does not propose to rename anything yet. It's only about the addition of the functions.

**Describe the solution you'd like**

We'd like to have three new functions (in BLAKE2b, BLAKE2s, BLAKE2bSimd, BLAKE2sSimd:

* `Hacl_Blake2b_32_blake2b_without_key` // Or some other name (see below)
* `Hacl_Streaming_Blake2_blake2b_32_create_in_with_key()` // Or some other name (see below)
* `Hacl_Streaming_Blake2_blake2b_32_init_with_key` // Or some other name (see below)

---

**Additional context**

*Changes (draft) that we will propose in a later PR*

| API                 | Current name                                            | Proposed new name                         |
|---------------------|---------------------------------------------------------|-------------------------------------------|
| One-Shot            | Not implemented yet                                     | Hacl_Hash_Blake2b_hash                    |
|                     | Hacl_Blake2b_32_blake2b                                 | Hacl_Hash_Blake2b_hash_with_key           |
| Streaming           | Hacl_Streaming_Blake2_blake2b_32_state                  | Hacl_Hash_Blake2b_state_t                 |
|                     | Hacl_Streaming_Blake2_blake2b_32_no_key_create_in()     | Hacl_Hash_Blake2b_malloc                  |
|                     | Not implemented yet                                     | Hacl_Hash_Blake2b_malloc_with_key         |
|                     | Hacl_Streaming_Blake2_blake2b_32_no_key_update          | Hacl_Hash_Blake2b_update                  |
|                     | Hacl_Streaming_Blake2_blake2b_32_no_key_finish          | Hacl_Hash_Blake2b_digest                  |
|                     | Hacl_Streaming_Blake2_blake2b_32_no_key_init            | Hacl_Hash_Blake2b_reset                   |
|                     | Not implemented yet                                     | Hacl_Hash_Blake2b_reset_with_key          |
|                     | Hacl_Streaming_Blake2_blake2b_32_no_key_free            | Hacl_Hash_Blake2b_free                    |
| One-Shot (simd256)  | Not implemented yet                                     | Hacl_Hash_Blake2b_Simd256_hash            |
|                     | Hacl_Blake2b_256_blake2b                                | Hacl_Hash_Blake2b_Simd256_hash_with_key   |
| Streaming (simd256) | Hacl_Streaming_Blake2b_256_blake2b_256_state            | Hacl_Hash_Blake2b_Simd256_state_t         |
|                     | Hacl_Streaming_Blake2b_256_blake2b_256_no_key_create_in | Hacl_Hash_Blake2b_Simd256_malloc          |
|                     | Not implemented yet                                     | Hacl_Hash_Blake2b_Simd256_malloc_with_key |
|                     | Hacl_Streaming_Blake2b_256_blake2b_256_no_key_update    | Hacl_Hash_Blake2b_Simd256_update          |
|                     | Hacl_Streaming_Blake2b_256_blake2b_256_no_key_finish    | Hacl_Hash_Blake2b_Simd256_digest          |
|                     | Hacl_Streaming_Blake2b_256_blake2b_256_no_key_init      | Hacl_Hash_Blake2b_Simd256_reset           |
|                     | Not implemented yet                                     | Hacl_Hash_Blake2b_Simd256_reset_with_key  |
|                     | Hacl_Streaming_Blake2b_256_blake2b_256_no_key_free      | Hacl_Hash_Blake2b_Simd256_free            |

**Comment by msprotz** [comment]
This is being fixed with the latest round of blake2 PRs. Closing -- thanks!
