### ISSUE TITLE
Update hacl-packages create branch CI

### ISSUE THREAD

**Issue by franziskuskiefer** [hacl-star/hacl-star#805]
Add js and ocaml to the hacl-packages CI flow.

https://github.com/hacl-star/hacl-star/blob/a8fce922a16ba4a8304f315032026a45916f850e/.github/workflows/hacl-packages-create-branch.yml#L37

Currently ocaml is broken and the CI didn't catch it because it is not updated.

**Comment by R1kM** [comment]
@franziskuskiefer This seems to have been fixed on the hacl-packages CI, can you please confirm this issue is not relevant anymore?

**Comment by franziskuskiefer** [comment]
Lets call this fixed for now. I'm not sure it's doing the right thing in all cases, but it generally works.
