### ISSUE TITLE
C code warnings

### ISSUE THREAD

**Issue by franziskuskiefer** [hacl-star/hacl-star#843]
**Describe the bug**
Building the C code generates a bunch of warnings that shouldn't be there.
To integrate the code into code bases that are strict on warnings these have to be eliminated.
See https://gist.github.com/franziskuskiefer/14f38f8ac1062d651a2e8d8aa99074c8 for a list of warnings.

**To Reproduce**
Build C sources with `-Wall -Wextra`

**Expected behavior**
No warnings

**Comment by karthik-cryspen** [comment]
We are working with Jonathan Protzenko to fix these upstream in KaRaMeL.
Maybe you can cross-file this issue there?

**Comment by franziskuskiefer** [comment]
Done 👆🏻

**Comment by msprotz** [comment]
Is set-but-not-used a must-fix? My understanding is that this is a pretty recent one

**Comment by franziskuskiefer** [comment]
> Is set-but-not-used a must-fix? My understanding is that this is a pretty recent one

It's a `Wall` warning that will be made into an error by most build systems.
Clang supports it since [13](https://releases.llvm.org/13.0.0/tools/clang/docs/DiagnosticsReference.html#wunused-but-set-variable) (Oct 21, we're at 16 now) and gcc [10](https://gcc.gnu.org/onlinedocs/gcc-10.5.0/gcc/Warning-Options.html) (May 20, EOL) as well. So I don't think you'll find many compilers out there that won't use/support it.

**Comment by prosecco** [comment]
The following patch proposed by @protz works well for all the unused-but-set warnings in HACL*.
```
diff --git a/dist/karamel/include/krml/internal/target.h b/dist/karamel/include/krml/internal/target.h
index 9eb260c630..a378ed4f4b 100644
--- a/dist/karamel/include/krml/internal/target.h
+++ b/dist/karamel/include/krml/internal/target.h
@@ -169,6 +169,7 @@ inline static int32_t krml_time(void) {
 #define KRML_LOOP1(i, n, x) { \
   x \
   i += n; \
+  (void) i; \
 }
 
 #define KRML_LOOP2(i, n, x) \
```

**Comment by msprotz** [comment]
Per https://github.com/FStarLang/karamel/issues/363, -Wimplicit-int-conversions is not covered by -Wall -Wextra, and is not commonly used, so let's punt on that for now. We can always fix the hand-written stuff in HACL that triggers the warning, then file an issue on the krml side to emit casts to defeat the warning (verbose). The other warnings are fixed and the code compiles with -Wall -Wextra, so closing this.
