### ISSUE TITLE
Missing alloca.h include for dist/mozilla

### ISSUE THREAD

**Issue by franziskuskiefer** [hacl-star/hacl-star#868]
This is a followup to #857.
Compilation fails on some systems when the `alloca.h` include is missing.
We can either add it during extraction, or modify `builtin.h` to include it. I'd vote to add it to the extraction to get a quick fix and then consider adding it to the `builtin.h`.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1857190 for the original bug report.

I don't know how to reproduce but it's on Solaris

**Comment by msprotz** [comment]
omg solaris really

**Comment by msprotz** [comment]
Fixed via #870
