### ISSUE TITLE
Documentation updates for Hashes?

### ISSUE THREAD

**Issue by simo5** [hacl-star/hacl-star#874]
It'd be really nice to have the Hashes documentation updated.
Especially for streaming APIs file names and Blake2.

Blake2 is particularly under-documented even in code, with surprising constraints (key length must not exceed 64 bytes or the stack gets overwritten) that are not documented even in the code files.

**Comment by msprotz** [comment]
We have plans to update streaming/blake2 in the short term with a better API that may or may not take a key, along with the usual safe streaming API. The absence of documentation for the key length assumption is indeed regrettable, sorry about that.

Can you say more about your use-case? This may inform us when we clean up streaming/blake2. Thanks!

**Comment by simo5** [comment]
I am trying to use it in my project because the Hacl_HMAC.c implementation wants Blake2 as all HMAC implementations are in a single file (my primary interested was HMAC with SHA functions), so given I had to import the Blake2 files anyway I was going to make the blake2b digest and HMAC available as well. I am implementing the PKCS#11 API which has a streaming interface and support BLAKE2B definitions.

I am indeed finding I need to reimplement things like *static void blake2b_update_blocks()* because the only really finished API seem to be the one-shot one.

I might give up for now, because implementing a streaming API with just _multi() and _last() available requires a lot of state to be kept around and buffers too.
Initially it seemed it was just under-documented, but it is under-developed too apparently.

**Comment by simo5** [comment]
I should have looked deeper in the HMAC implementation, as it lacks the streaming counterpart too ... oh well.
Hopefully one day it will come.

**Comment by simo5** [comment]
> FYI, there is more documentation here that may help you navigate the various modules: https://cryspen.com/hacl-packages/c/main/index.html

Thanks you this is very handy.

**Comment by R1kM** [comment]
Closing this, but please do reopen if you have additional questions
