### ISSUE TITLE
RSAPSS available in Code, but not in dist?

### ISSUE THREAD

**Issue by simo5** [hacl-star/hacl-star#875]
Curious as to why there seem to be an implementation of RSAPSS under code/ but no translation of it under dist/ ...

**Comment by polubelova** [comment]
The implementation of RSAPSS can be found, for example, [here](https://github.com/hacl-star/hacl-star/blob/main/dist/gcc-compatible/Hacl_RSAPSS.h). It is also available for the `portable-gcc-compatible` and `msvc-compatible` distributions.

**Comment by simo5** [comment]
Looks like today I am blind, sorry for the noise.
